"""add_source_config_and_discovery_metrics

Revision ID: 14b124e0e1a4
Revises: '289043dd9df3'
Create Date: 2026-08-22 00:40:02.706662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14b124e0e1a4'
down_revision: Union[str, None] = '289043dd9df3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('discovery_enabled', sa.Boolean(), nullable=False),
    sa.Column('application_enabled', sa.Boolean(), nullable=False),
    sa.Column('max_jobs_per_run', sa.Integer(), nullable=False),
    sa.Column('max_pages_per_run', sa.Integer(), nullable=False),
    sa.Column('rate_limit', sa.Float(), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['job_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id')
    )
    op.create_index(op.f('ix_source_configurations_id'), 'source_configurations', ['id'], unique=False)
    op.add_column('job_discovery_runs', sa.Column('pages_visited', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('job_discovery_runs', sa.Column('requests_made', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('job_discovery_runs', sa.Column('rate_limit_events', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('job_discovery_runs', sa.Column('authentication_events', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('job_discovery_runs', sa.Column('source_status', sa.String(length=50), nullable=False, server_default='healthy'))
    op.add_column('job_discovery_runs', sa.Column('stale_jobs', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('jobs', sa.Column('source_updated_at', sa.DateTime(), nullable=True))
    op.add_column('jobs', sa.Column('last_seen_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.add_column('jobs', sa.Column('url_status', sa.String(length=50), nullable=False, server_default='UNKNOWN'))
    op.add_column('jobs', sa.Column('url_verified_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'url_verified_at')
    op.drop_column('jobs', 'url_status')
    op.drop_column('jobs', 'last_seen_at')
    op.drop_column('jobs', 'source_updated_at')
    op.drop_column('job_discovery_runs', 'stale_jobs')
    op.drop_column('job_discovery_runs', 'source_status')
    op.drop_column('job_discovery_runs', 'authentication_events')
    op.drop_column('job_discovery_runs', 'rate_limit_events')
    op.drop_column('job_discovery_runs', 'requests_made')
    op.drop_column('job_discovery_runs', 'pages_visited')
    op.drop_index(op.f('ix_source_configurations_id'), table_name='source_configurations')
    op.drop_table('source_configurations')
    # ### end Alembic commands ###
