"""create_job_tables

Revision ID: 221fac96b4fb
Revises: '477544d0eea4'
Create Date: 2026-08-21 12:22:29.538290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '221fac96b4fb'
down_revision: Union[str, None] = '477544d0eea4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_successful_run', sa.DateTime(), nullable=True),
    sa.Column('last_failed_run', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_sources_id'), 'job_sources', ['id'], unique=False)
    op.create_index(op.f('ix_job_sources_name'), 'job_sources', ['name'], unique=True)
    op.create_table('job_discovery_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('jobs_discovered', sa.Integer(), nullable=False),
    sa.Column('jobs_created', sa.Integer(), nullable=False),
    sa.Column('jobs_updated', sa.Integer(), nullable=False),
    sa.Column('duplicates', sa.Integer(), nullable=False),
    sa.Column('invalid_jobs', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['job_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_discovery_runs_id'), 'job_discovery_runs', ['id'], unique=False)
    op.create_table('raw_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('external_job_id', sa.String(length=255), nullable=True),
    sa.Column('raw_title', sa.String(length=255), nullable=True),
    sa.Column('raw_company', sa.String(length=255), nullable=True),
    sa.Column('raw_location', sa.String(length=255), nullable=True),
    sa.Column('raw_description', sa.Text(), nullable=True),
    sa.Column('raw_url', sa.String(length=1000), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['job_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_jobs_external_job_id'), 'raw_jobs', ['external_job_id'], unique=False)
    op.create_index(op.f('ix_raw_jobs_id'), 'raw_jobs', ['id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_job_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('external_job_id', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('company_url', sa.String(length=500), nullable=True),
    sa.Column('job_url', sa.String(length=1000), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('normalized_location', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('employment_type', sa.String(length=50), nullable=False),
    sa.Column('workplace_type', sa.String(length=50), nullable=False),
    sa.Column('experience_min', sa.Float(), nullable=True),
    sa.Column('experience_max', sa.Float(), nullable=True),
    sa.Column('salary_min', sa.Float(), nullable=True),
    sa.Column('salary_max', sa.Float(), nullable=True),
    sa.Column('salary_currency', sa.String(length=10), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('application_url', sa.String(length=1000), nullable=True),
    sa.Column('source_metadata', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['raw_job_id'], ['raw_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['job_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_company_name'), 'jobs', ['company_name'], unique=False)
    op.create_index(op.f('ix_jobs_employment_type'), 'jobs', ['employment_type'], unique=False)
    op.create_index(op.f('ix_jobs_external_job_id'), 'jobs', ['external_job_id'], unique=False)
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.create_index(op.f('ix_jobs_job_url'), 'jobs', ['job_url'], unique=False)
    op.create_index(op.f('ix_jobs_normalized_location'), 'jobs', ['normalized_location'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_title'), 'jobs', ['title'], unique=False)
    op.create_index(op.f('ix_jobs_workplace_type'), 'jobs', ['workplace_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_workplace_type'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_title'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_normalized_location'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_job_url'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_external_job_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_employment_type'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_company_name'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_raw_jobs_id'), table_name='raw_jobs')
    op.drop_index(op.f('ix_raw_jobs_external_job_id'), table_name='raw_jobs')
    op.drop_table('raw_jobs')
    op.drop_index(op.f('ix_job_discovery_runs_id'), table_name='job_discovery_runs')
    op.drop_table('job_discovery_runs')
    op.drop_index(op.f('ix_job_sources_name'), table_name='job_sources')
    op.drop_index(op.f('ix_job_sources_id'), table_name='job_sources')
    op.drop_table('job_sources')
    # ### end Alembic commands ###
