"""create_application_control_tables

Revision ID: 289043dd9df3
Revises: 'fd31e8d2b421'
Create Date: 2026-08-22 00:15:18.023286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '289043dd9df3'
down_revision: Union[str, None] = 'fd31e8d2b421'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('application_package_id', sa.Integer(), nullable=True),
    sa.Column('selected_resume_id', sa.Integer(), nullable=True),
    sa.Column('tailored_resume_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('application_url', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['application_package_id'], ['application_packages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_id'], ['job_matches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selected_resume_id'], ['resumes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tailored_resume_id'], ['tailored_resumes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_application_package_id'), 'applications', ['application_package_id'], unique=False)
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    op.create_index(op.f('ix_applications_job_id'), 'applications', ['job_id'], unique=False)
    op.create_index(op.f('ix_applications_match_id'), 'applications', ['match_id'], unique=False)
    op.create_index(op.f('ix_applications_profile_id'), 'applications', ['profile_id'], unique=False)
    op.create_index(op.f('ix_applications_selected_resume_id'), 'applications', ['selected_resume_id'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_index(op.f('ix_applications_tailored_resume_id'), 'applications', ['tailored_resume_id'], unique=False)
    op.create_table('package_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_package_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('package_content', sa.JSON(), nullable=False),
    sa.Column('change_reason', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_package_id'], ['application_packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_package_versions_application_package_id'), 'package_versions', ['application_package_id'], unique=False)
    op.create_index(op.f('ix_package_versions_id'), 'package_versions', ['id'], unique=False)
    op.create_table('application_approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('package_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('reviewer', sa.String(length=100), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_approvals_application_id'), 'application_approvals', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_approvals_id'), 'application_approvals', ['id'], unique=False)
    op.create_index(op.f('ix_application_approvals_status'), 'application_approvals', ['status'], unique=False)
    op.create_table('application_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_audit_logs_application_id'), 'application_audit_logs', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_audit_logs_event_type'), 'application_audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_application_audit_logs_id'), 'application_audit_logs', ['id'], unique=False)
    op.create_table('application_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('profile_snapshot', sa.JSON(), nullable=False),
    sa.Column('job_snapshot', sa.JSON(), nullable=False),
    sa.Column('match_snapshot', sa.JSON(), nullable=False),
    sa.Column('resume_snapshot', sa.JSON(), nullable=False),
    sa.Column('answers_snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_snapshots_application_id'), 'application_snapshots', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_snapshots_id'), 'application_snapshots', ['id'], unique=False)
    op.create_table('submission_authorizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('package_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('authorized_by', sa.String(length=100), nullable=False),
    sa.Column('authorized_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submission_authorizations_application_id'), 'submission_authorizations', ['application_id'], unique=False)
    op.create_index(op.f('ix_submission_authorizations_id'), 'submission_authorizations', ['id'], unique=False)
    op.create_index(op.f('ix_submission_authorizations_status'), 'submission_authorizations', ['status'], unique=False)
    op.create_table('submission_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('authorization_id', sa.Integer(), nullable=True),
    sa.Column('adapter', sa.String(length=100), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('submission_id', sa.String(length=255), nullable=True),
    sa.Column('confirmation', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['authorization_id'], ['submission_authorizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submission_runs_application_id'), 'submission_runs', ['application_id'], unique=False)
    op.create_index(op.f('ix_submission_runs_authorization_id'), 'submission_runs', ['authorization_id'], unique=False)
    op.create_index(op.f('ix_submission_runs_id'), 'submission_runs', ['id'], unique=False)
    op.create_index(op.f('ix_submission_runs_status'), 'submission_runs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submission_runs_status'), table_name='submission_runs')
    op.drop_index(op.f('ix_submission_runs_id'), table_name='submission_runs')
    op.drop_index(op.f('ix_submission_runs_authorization_id'), table_name='submission_runs')
    op.drop_index(op.f('ix_submission_runs_application_id'), table_name='submission_runs')
    op.drop_table('submission_runs')
    op.drop_index(op.f('ix_submission_authorizations_status'), table_name='submission_authorizations')
    op.drop_index(op.f('ix_submission_authorizations_id'), table_name='submission_authorizations')
    op.drop_index(op.f('ix_submission_authorizations_application_id'), table_name='submission_authorizations')
    op.drop_table('submission_authorizations')
    op.drop_index(op.f('ix_application_snapshots_id'), table_name='application_snapshots')
    op.drop_index(op.f('ix_application_snapshots_application_id'), table_name='application_snapshots')
    op.drop_table('application_snapshots')
    op.drop_index(op.f('ix_application_audit_logs_id'), table_name='application_audit_logs')
    op.drop_index(op.f('ix_application_audit_logs_event_type'), table_name='application_audit_logs')
    op.drop_index(op.f('ix_application_audit_logs_application_id'), table_name='application_audit_logs')
    op.drop_table('application_audit_logs')
    op.drop_index(op.f('ix_application_approvals_status'), table_name='application_approvals')
    op.drop_index(op.f('ix_application_approvals_id'), table_name='application_approvals')
    op.drop_index(op.f('ix_application_approvals_application_id'), table_name='application_approvals')
    op.drop_table('application_approvals')
    op.drop_index(op.f('ix_package_versions_id'), table_name='package_versions')
    op.drop_index(op.f('ix_package_versions_application_package_id'), table_name='package_versions')
    op.drop_table('package_versions')
    op.drop_index(op.f('ix_applications_tailored_resume_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_selected_resume_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_profile_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_match_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_job_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_application_package_id'), table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
