"""create_screening_question_tables

Revision ID: 2ba72b12c4b6
Revises: 'c9dc6936452f'
Create Date: 2026-08-21 16:35:36.592541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ba72b12c4b6'
down_revision: Union[str, None] = 'c9dc6936452f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer_memories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=100), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('user_approved', sa.Boolean(), nullable=False),
    sa.Column('reusable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_memories_id'), 'answer_memories', ['id'], unique=False)
    op.create_index(op.f('ix_answer_memories_profile_id'), 'answer_memories', ['profile_id'], unique=False)
    op.create_index(op.f('ix_answer_memories_question_type'), 'answer_memories', ['question_type'], unique=False)
    op.create_table('application_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('automation_run_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('field_identifier', sa.String(length=255), nullable=True),
    sa.Column('question_type', sa.String(length=100), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('classification_confidence', sa.Float(), nullable=False),
    sa.Column('answer_source', sa.String(length=50), nullable=False),
    sa.Column('max_length', sa.Integer(), nullable=True),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['automation_run_id'], ['automation_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_questions_automation_run_id'), 'application_questions', ['automation_run_id'], unique=False)
    op.create_index(op.f('ix_application_questions_id'), 'application_questions', ['id'], unique=False)
    op.create_index(op.f('ix_application_questions_job_id'), 'application_questions', ['job_id'], unique=False)
    op.create_index(op.f('ix_application_questions_question_type'), 'application_questions', ['question_type'], unique=False)
    op.create_table('application_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('answer_status', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('generated_by', sa.String(length=50), nullable=False),
    sa.Column('validation_result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['application_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_answers_answer_status'), 'application_answers', ['answer_status'], unique=False)
    op.create_index(op.f('ix_application_answers_id'), 'application_answers', ['id'], unique=False)
    op.create_index(op.f('ix_application_answers_question_id'), 'application_answers', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_answers_question_id'), table_name='application_answers')
    op.drop_index(op.f('ix_application_answers_id'), table_name='application_answers')
    op.drop_index(op.f('ix_application_answers_answer_status'), table_name='application_answers')
    op.drop_table('application_answers')
    op.drop_index(op.f('ix_application_questions_question_type'), table_name='application_questions')
    op.drop_index(op.f('ix_application_questions_job_id'), table_name='application_questions')
    op.drop_index(op.f('ix_application_questions_id'), table_name='application_questions')
    op.drop_index(op.f('ix_application_questions_automation_run_id'), table_name='application_questions')
    op.drop_table('application_questions')
    op.drop_index(op.f('ix_answer_memories_question_type'), table_name='answer_memories')
    op.drop_index(op.f('ix_answer_memories_profile_id'), table_name='answer_memories')
    op.drop_index(op.f('ix_answer_memories_id'), table_name='answer_memories')
    op.drop_table('answer_memories')
    # ### end Alembic commands ###
