"""add_phase_11_application_models

Revision ID: 92dac00f6926
Revises: '14b124e0e1a4'
Create Date: 2026-08-22 00:51:39.814502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92dac00f6926'
down_revision: Union[str, None] = '14b124e0e1a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_source_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('mode', sa.String(length=50), nullable=False),
    sa.Column('allowed_domains', sa.JSON(), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('max_applications_per_run', sa.Integer(), nullable=False),
    sa.Column('max_applications_per_day', sa.Integer(), nullable=False),
    sa.Column('max_failed_attempts', sa.Integer(), nullable=False),
    sa.Column('max_human_interventions', sa.Integer(), nullable=False),
    sa.Column('require_human_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['job_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_source_configurations_id'), 'application_source_configurations', ['id'], unique=False)
    op.create_index(op.f('ix_application_source_configurations_source_id'), 'application_source_configurations', ['source_id'], unique=True)
    op.create_table('application_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('queued_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_queue_application_id'), 'application_queue', ['application_id'], unique=True)
    op.create_index(op.f('ix_application_queue_id'), 'application_queue', ['id'], unique=False)
    op.create_index(op.f('ix_application_queue_status'), 'application_queue', ['status'], unique=False)
    op.create_table('human_intervention_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('automation_run_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['automation_run_id'], ['automation_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_human_intervention_events_application_id'), 'human_intervention_events', ['application_id'], unique=False)
    op.create_index(op.f('ix_human_intervention_events_automation_run_id'), 'human_intervention_events', ['automation_run_id'], unique=False)
    op.create_index(op.f('ix_human_intervention_events_id'), 'human_intervention_events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_human_intervention_events_id'), table_name='human_intervention_events')
    op.drop_index(op.f('ix_human_intervention_events_automation_run_id'), table_name='human_intervention_events')
    op.drop_index(op.f('ix_human_intervention_events_application_id'), table_name='human_intervention_events')
    op.drop_table('human_intervention_events')
    op.drop_index(op.f('ix_application_queue_status'), table_name='application_queue')
    op.drop_index(op.f('ix_application_queue_id'), table_name='application_queue')
    op.drop_index(op.f('ix_application_queue_application_id'), table_name='application_queue')
    op.drop_table('application_queue')
    op.drop_index(op.f('ix_application_source_configurations_source_id'), table_name='application_source_configurations')
    op.drop_index(op.f('ix_application_source_configurations_id'), table_name='application_source_configurations')
    op.drop_table('application_source_configurations')
    # ### end Alembic commands ###
