"""add_phase_12_orchestration_models

Revision ID: be68281f1ea3
Revises: '92dac00f6926'
Create Date: 2026-08-22 01:00:19.581079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be68281f1ea3'
down_revision: Union[str, None] = '92dac00f6926'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('preset_name', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('discovery_enabled', sa.Boolean(), nullable=False),
    sa.Column('discovery_sources', sa.JSON(), nullable=False),
    sa.Column('max_jobs_per_run', sa.Integer(), nullable=False),
    sa.Column('minimum_match_score', sa.Float(), nullable=False),
    sa.Column('allowed_recommendations', sa.JSON(), nullable=False),
    sa.Column('auto_tailor_resume', sa.Boolean(), nullable=False),
    sa.Column('auto_generate_answers', sa.Boolean(), nullable=False),
    sa.Column('require_human_review', sa.Boolean(), nullable=False),
    sa.Column('auto_approve', sa.Boolean(), nullable=False),
    sa.Column('allowed_modes', sa.JSON(), nullable=False),
    sa.Column('max_applications_per_run', sa.Integer(), nullable=False),
    sa.Column('max_applications_per_day', sa.Integer(), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('cooldown_days', sa.Integer(), nullable=False),
    sa.Column('concurrency_limit', sa.Integer(), nullable=False),
    sa.Column('priority_weights', sa.JSON(), nullable=False),
    sa.Column('authorization_expiration_hours', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_configurations_id'), 'automation_configurations', ['id'], unique=False)
    op.create_index(op.f('ix_automation_configurations_profile_id'), 'automation_configurations', ['profile_id'], unique=True)
    op.create_table('daily_automation_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('jobs_discovered', sa.Integer(), nullable=False),
    sa.Column('jobs_matched', sa.Integer(), nullable=False),
    sa.Column('applications_prepared', sa.Integer(), nullable=False),
    sa.Column('applications_submitted', sa.Integer(), nullable=False),
    sa.Column('applications_failed', sa.Integer(), nullable=False),
    sa.Column('average_match_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_automation_metrics_date'), 'daily_automation_metrics', ['date'], unique=False)
    op.create_index(op.f('ix_daily_automation_metrics_id'), 'daily_automation_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_daily_automation_metrics_profile_id'), 'daily_automation_metrics', ['profile_id'], unique=False)
    op.create_table('orchestration_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('jobs_discovered', sa.Integer(), nullable=False),
    sa.Column('jobs_matched', sa.Integer(), nullable=False),
    sa.Column('jobs_selected', sa.Integer(), nullable=False),
    sa.Column('packages_created', sa.Integer(), nullable=False),
    sa.Column('applications_ready', sa.Integer(), nullable=False),
    sa.Column('applications_approved', sa.Integer(), nullable=False),
    sa.Column('applications_queued', sa.Integer(), nullable=False),
    sa.Column('applications_submitted', sa.Integer(), nullable=False),
    sa.Column('applications_failed', sa.Integer(), nullable=False),
    sa.Column('applications_paused', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('configuration_version', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orchestration_runs_id'), 'orchestration_runs', ['id'], unique=False)
    op.create_index(op.f('ix_orchestration_runs_profile_id'), 'orchestration_runs', ['profile_id'], unique=False)
    op.create_index(op.f('ix_orchestration_runs_status'), 'orchestration_runs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orchestration_runs_status'), table_name='orchestration_runs')
    op.drop_index(op.f('ix_orchestration_runs_profile_id'), table_name='orchestration_runs')
    op.drop_index(op.f('ix_orchestration_runs_id'), table_name='orchestration_runs')
    op.drop_table('orchestration_runs')
    op.drop_index(op.f('ix_daily_automation_metrics_profile_id'), table_name='daily_automation_metrics')
    op.drop_index(op.f('ix_daily_automation_metrics_id'), table_name='daily_automation_metrics')
    op.drop_index(op.f('ix_daily_automation_metrics_date'), table_name='daily_automation_metrics')
    op.drop_table('daily_automation_metrics')
    op.drop_index(op.f('ix_automation_configurations_profile_id'), table_name='automation_configurations')
    op.drop_index(op.f('ix_automation_configurations_id'), table_name='automation_configurations')
    op.drop_table('automation_configurations')
    # ### end Alembic commands ###
