"""create_automation_tables

Revision ID: c9dc6936452f
Revises: 'efc71220df35'
Create Date: 2026-08-21 16:24:22.571515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9dc6936452f'
down_revision: Union[str, None] = 'efc71220df35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_url', sa.String(length=500), nullable=True),
    sa.Column('actions_attempted', sa.Integer(), nullable=False),
    sa.Column('actions_completed', sa.Integer(), nullable=False),
    sa.Column('actions_failed', sa.Integer(), nullable=False),
    sa.Column('human_intervention_required', sa.Boolean(), nullable=False),
    sa.Column('pause_reason', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('screenshots', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_runs_human_intervention_required'), 'automation_runs', ['human_intervention_required'], unique=False)
    op.create_index(op.f('ix_automation_runs_id'), 'automation_runs', ['id'], unique=False)
    op.create_index(op.f('ix_automation_runs_job_id'), 'automation_runs', ['job_id'], unique=False)
    op.create_index(op.f('ix_automation_runs_profile_id'), 'automation_runs', ['profile_id'], unique=False)
    op.create_index(op.f('ix_automation_runs_state'), 'automation_runs', ['state'], unique=False)
    op.create_table('action_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('automation_run_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('field_type', sa.String(length=100), nullable=True),
    sa.Column('target_selector', sa.String(length=255), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('value_present', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['automation_run_id'], ['automation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_logs_automation_run_id'), 'action_logs', ['automation_run_id'], unique=False)
    op.create_index(op.f('ix_action_logs_id'), 'action_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_action_logs_id'), table_name='action_logs')
    op.drop_index(op.f('ix_action_logs_automation_run_id'), table_name='action_logs')
    op.drop_table('action_logs')
    op.drop_index(op.f('ix_automation_runs_state'), table_name='automation_runs')
    op.drop_index(op.f('ix_automation_runs_profile_id'), table_name='automation_runs')
    op.drop_index(op.f('ix_automation_runs_job_id'), table_name='automation_runs')
    op.drop_index(op.f('ix_automation_runs_id'), table_name='automation_runs')
    op.drop_index(op.f('ix_automation_runs_human_intervention_required'), table_name='automation_runs')
    op.drop_table('automation_runs')
    # ### end Alembic commands ###
