"""create_matching_tables

Revision ID: efc71220df35
Revises: '221fac96b4fb'
Create Date: 2026-08-21 16:16:00.978813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efc71220df35'
down_revision: Union[str, None] = '221fac96b4fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('weight_skills', sa.Float(), nullable=False),
    sa.Column('weight_role', sa.Float(), nullable=False),
    sa.Column('weight_experience', sa.Float(), nullable=False),
    sa.Column('weight_location', sa.Float(), nullable=False),
    sa.Column('weight_workplace', sa.Float(), nullable=False),
    sa.Column('weight_employment', sa.Float(), nullable=False),
    sa.Column('weight_education', sa.Float(), nullable=False),
    sa.Column('weight_semantic', sa.Float(), nullable=False),
    sa.Column('threshold_apply', sa.Float(), nullable=False),
    sa.Column('threshold_review', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id')
    )
    op.create_index(op.f('ix_match_configs_id'), 'match_configs', ['id'], unique=False)
    op.create_table('match_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('jobs_evaluated', sa.Integer(), nullable=False),
    sa.Column('jobs_eligible', sa.Integer(), nullable=False),
    sa.Column('apply_count', sa.Integer(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('skip_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_runs_id'), 'match_runs', ['id'], unique=False)
    op.create_table('job_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('recommendation', sa.String(length=20), nullable=False),
    sa.Column('eligible', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('matcher_version', sa.String(length=20), nullable=False),
    sa.Column('component_scores', sa.JSON(), nullable=False),
    sa.Column('hard_failures', sa.JSON(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('strengths', sa.JSON(), nullable=False),
    sa.Column('concerns', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_matches_eligible'), 'job_matches', ['eligible'], unique=False)
    op.create_index(op.f('ix_job_matches_id'), 'job_matches', ['id'], unique=False)
    op.create_index(op.f('ix_job_matches_job_id'), 'job_matches', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_matches_overall_score'), 'job_matches', ['overall_score'], unique=False)
    op.create_index(op.f('ix_job_matches_profile_id'), 'job_matches', ['profile_id'], unique=False)
    op.create_index(op.f('ix_job_matches_recommendation'), 'job_matches', ['recommendation'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_matches_recommendation'), table_name='job_matches')
    op.drop_index(op.f('ix_job_matches_profile_id'), table_name='job_matches')
    op.drop_index(op.f('ix_job_matches_overall_score'), table_name='job_matches')
    op.drop_index(op.f('ix_job_matches_job_id'), table_name='job_matches')
    op.drop_index(op.f('ix_job_matches_id'), table_name='job_matches')
    op.drop_index(op.f('ix_job_matches_eligible'), table_name='job_matches')
    op.drop_table('job_matches')
    op.drop_index(op.f('ix_match_runs_id'), table_name='match_runs')
    op.drop_table('match_runs')
    op.drop_index(op.f('ix_match_configs_id'), table_name='match_configs')
    op.drop_table('match_configs')
    # ### end Alembic commands ###
