"""create_tailored_resume_tables

Revision ID: fd31e8d2b421
Revises: '2ba72b12c4b6'
Create Date: 2026-08-21 23:55:45.663865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd31e8d2b421'
down_revision: Union[str, None] = '2ba72b12c4b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_tailoring_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('requirements_found', sa.Integer(), nullable=False),
    sa.Column('evidence_items', sa.Integer(), nullable=False),
    sa.Column('changes_count', sa.Integer(), nullable=False),
    sa.Column('validation_status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_tailoring_runs_id'), 'resume_tailoring_runs', ['id'], unique=False)
    op.create_index(op.f('ix_resume_tailoring_runs_job_id'), 'resume_tailoring_runs', ['job_id'], unique=False)
    op.create_index(op.f('ix_resume_tailoring_runs_profile_id'), 'resume_tailoring_runs', ['profile_id'], unique=False)
    op.create_index(op.f('ix_resume_tailoring_runs_resume_id'), 'resume_tailoring_runs', ['resume_id'], unique=False)
    op.create_index(op.f('ix_resume_tailoring_runs_status'), 'resume_tailoring_runs', ['status'], unique=False)
    op.create_table('tailored_resumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('source_resume_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('pdf_file_path', sa.String(length=512), nullable=True),
    sa.Column('docx_file_path', sa.String(length=512), nullable=True),
    sa.Column('structured_content', sa.JSON(), nullable=False),
    sa.Column('change_report', sa.JSON(), nullable=False),
    sa.Column('keyword_analysis', sa.JSON(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_id'], ['job_matches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_resume_id'], ['resumes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tailored_resumes_id'), 'tailored_resumes', ['id'], unique=False)
    op.create_index(op.f('ix_tailored_resumes_job_id'), 'tailored_resumes', ['job_id'], unique=False)
    op.create_index(op.f('ix_tailored_resumes_match_id'), 'tailored_resumes', ['match_id'], unique=False)
    op.create_index(op.f('ix_tailored_resumes_profile_id'), 'tailored_resumes', ['profile_id'], unique=False)
    op.create_index(op.f('ix_tailored_resumes_source_resume_id'), 'tailored_resumes', ['source_resume_id'], unique=False)
    op.create_index(op.f('ix_tailored_resumes_status'), 'tailored_resumes', ['status'], unique=False)
    op.create_table('application_packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('source_resume_id', sa.Integer(), nullable=True),
    sa.Column('tailored_resume_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('package_summary', sa.JSON(), nullable=False),
    sa.Column('validation_result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_resume_id'], ['resumes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tailored_resume_id'], ['tailored_resumes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_packages_id'), 'application_packages', ['id'], unique=False)
    op.create_index(op.f('ix_application_packages_job_id'), 'application_packages', ['job_id'], unique=False)
    op.create_index(op.f('ix_application_packages_profile_id'), 'application_packages', ['profile_id'], unique=False)
    op.create_index(op.f('ix_application_packages_source_resume_id'), 'application_packages', ['source_resume_id'], unique=False)
    op.create_index(op.f('ix_application_packages_status'), 'application_packages', ['status'], unique=False)
    op.create_index(op.f('ix_application_packages_tailored_resume_id'), 'application_packages', ['tailored_resume_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_packages_tailored_resume_id'), table_name='application_packages')
    op.drop_index(op.f('ix_application_packages_status'), table_name='application_packages')
    op.drop_index(op.f('ix_application_packages_source_resume_id'), table_name='application_packages')
    op.drop_index(op.f('ix_application_packages_profile_id'), table_name='application_packages')
    op.drop_index(op.f('ix_application_packages_job_id'), table_name='application_packages')
    op.drop_index(op.f('ix_application_packages_id'), table_name='application_packages')
    op.drop_table('application_packages')
    op.drop_index(op.f('ix_tailored_resumes_status'), table_name='tailored_resumes')
    op.drop_index(op.f('ix_tailored_resumes_source_resume_id'), table_name='tailored_resumes')
    op.drop_index(op.f('ix_tailored_resumes_profile_id'), table_name='tailored_resumes')
    op.drop_index(op.f('ix_tailored_resumes_match_id'), table_name='tailored_resumes')
    op.drop_index(op.f('ix_tailored_resumes_job_id'), table_name='tailored_resumes')
    op.drop_index(op.f('ix_tailored_resumes_id'), table_name='tailored_resumes')
    op.drop_table('tailored_resumes')
    op.drop_index(op.f('ix_resume_tailoring_runs_status'), table_name='resume_tailoring_runs')
    op.drop_index(op.f('ix_resume_tailoring_runs_resume_id'), table_name='resume_tailoring_runs')
    op.drop_index(op.f('ix_resume_tailoring_runs_profile_id'), table_name='resume_tailoring_runs')
    op.drop_index(op.f('ix_resume_tailoring_runs_job_id'), table_name='resume_tailoring_runs')
    op.drop_index(op.f('ix_resume_tailoring_runs_id'), table_name='resume_tailoring_runs')
    op.drop_table('resume_tailoring_runs')
    # ### end Alembic commands ###
